image: maven:3.9-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

test:
  stage: test
  script:
    - mvn test

deploy_railway:
  stage: deploy
  image: ubuntu:latest
  before_script:
    # Installation des dépendances nécessaires
    - apt-get update
    - apt-get install -y curl
    # Installation de Railway CLI
    - curl -fsSL https://railway.app/install.sh | sh
  script:
    # Déploiement avec token direct
    - railway up --token "${RAILWAY_TOKEN}" --service "${SERVICE_NAME}"
  only:
    - main  # ou master, selon votre branche principale
  environment:
    name: production
  variables:
    GIT_STRATEGY: none  # On n'a pas besoin de récupérer le code ici car on a les artifacts 